export const detailData = [
    'EARTHLAB CBD AMPOULE SERUM', '9CE CBD BRIGHTENING AMPOULE', '9CE CBD CREAM', "EARTH LAB CBD DE'LEEP", 'EARTHLAB CBD GREEN ANGEL HERBAL CREAM', 'MCT OIL PLUS',
    '9CE CBD DEEP SLEEPING CREAM', '9CE DD & SUNSCREEN', 'EARTHLAB CBD WHITENING MASK'
]